name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        working-directory: front-end
        run: npm ci

      - name: Run Tests
        working-directory: front-end
        run: npm test